### ISSUE TITLE
Unpromoted pawn at the second last row is unable to move

### ISSUE THREAD

**Issue by lekhachuy08** [murosan/shogi-board#4]
If a pawn is moved to the second last row and is not promoted, it will be unable to move.
<img width="804" alt="shogi-board" src="https://user-images.githubusercontent.com/16387471/41818180-84216e48-77ec-11e8-97cf-5006f211fb92.png">

**Comment by ngocdaothanh** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/Shogi#Promotion) (I'm not sure if it's related to the bug):

If a pawn or lance is moved to the furthest rank, or a knight is moved to either of the two furthest ranks, that piece must promote (otherwise, it would have no legal move on subsequent turns). A silver general is never required to promote

**Comment by murosan** [comment]
This is bug. fixed [commit #150](https://github.com/murosan/shogi-board/commit/b0c7594fdf25e79da22971111b74cd964d57b234)
